version: '3.8'
services:
  mysql-films:
    image: samuelgarciahub/tfg-mysql-films #nombre de la imagen que hemos creado
    restart: always
    container_name: mysql-films
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: films
  mysql-series:
    image: samuelgarciahub/tfg-mysql-series #nombre de la imagen que hemos creado
    restart: always
    container_name: mysql-series
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: series
      MYSQL_TCP_PORT: 3307
  mysql-reviews:
    image: samuelgarciahub/tfg-mysql-reviews #nombre de la imagen que hemos creado
    restart: always
    container_name: mysql-reviews
    ports:
      - '3308:3308'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reviews
      MYSQL_TCP_PORT: 3308