spring:
  application:
    name: zuul-service
server:
  port: 7000
zuul:
  routes:
      serv-films: 
        path: /films-service/** 
        serviceId: films-service        
        url: http://localhost:8001
      #  http://localhost:7000/films-service/films/
      serv-series: 
        path: /series-service/** 
        serviceId: series-service
        url: http://localhost:8002
      #  http://localhost:7000/series-service/
      serv-search:
        path: /search-service/** 
        serviceId: search-service
        url: http://localhost:9000
      #  http://localhost:7000/search-service/
      serv-review:
        path: /review-service/**
        serviceId: review-service
        url: http://localhost:8003
      #  http://localhost:7000/review-service/
      
eureka: 
  client:
    serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka